#!/usr/bin/env bash
# Regenerates brewfile.core (work profile) from brewfile.
#
# Rules:
#   tap   - "buo/cask-upgrade" (needed by the bup alias) plus any tap listed
#           in core_include.txt
#   brew  - everything except names listed in core_exclude.txt; tap-scoped
#           formulae (name contains "/") are dropped unless listed in
#           core_include.txt, since their taps are not installed on work
#           machines otherwise
#   cask  - nerd fonts (terminal icons/prompt glyphs) plus anything listed
#           in core_include.txt
#   mas / vscode - dropped
#
# Runs automatically from the bdp alias (after every dump) and from
# brew/_setup.sh when the work profile installs.

set -euo pipefail

BREW_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
SRC="$BREW_DIR/brewfile"
EXCLUDE_FILE="$BREW_DIR/core_exclude.txt"
INCLUDE_FILE="$BREW_DIR/core_include.txt"
OUT="$BREW_DIR/brewfile.core"

{
  echo "# AUTO-GENERATED by generate_core.sh from brewfile - DO NOT EDIT."
  echo "# To keep a formula off the work profile, add it to core_exclude.txt."
  echo "# To force a cask/tap/tap-scoped formula onto the work profile, add it to core_include.txt."
  echo ""
  awk -v exclude_file="$EXCLUDE_FILE" -v include_file="$INCLUDE_FILE" '
    BEGIN {
      while ((getline line < exclude_file) > 0) {
        sub(/#.*$/, "", line)
        gsub(/^[ \t]+|[ \t]+$/, "", line)
        if (line != "") excl[line] = 1
      }
      close(exclude_file)
      while ((getline line < include_file) > 0) {
        sub(/#.*$/, "", line)
        gsub(/^[ \t]+|[ \t]+$/, "", line)
        if (line != "") incl[line] = 1
      }
      close(include_file)
    }
    /^#/ { comment = $0; next }
    /^tap "/ {
      name = $0
      sub(/^tap "/, "", name)
      sub(/".*$/, "", name)
      if (name == "buo/cask-upgrade" || (name in incl)) {
        if (comment != "") print comment
        print
      }
      comment = ""
      next
    }
    /^brew "/ {
      name = $0
      sub(/^brew "/, "", name)
      sub(/".*$/, "", name)
      if (!(name in excl) && (name !~ /\// || (name in incl))) {
        if (comment != "") print comment
        print
      }
      comment = ""
      next
    }
    /^cask "/ {
      name = $0
      sub(/^cask "/, "", name)
      sub(/".*$/, "", name)
      if (name ~ /^font-[^"]*nerd[^"]*$/ || (name in incl)) {
        if (comment != "") print comment
        print
      }
      comment = ""
      next
    }
    { comment = "" }
  ' "$SRC"
} > "$OUT"

echo "✅ brewfile.core: $(grep -c '^brew ' "$OUT") formulae, $(grep -c '^cask ' "$OUT") casks"
