"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => CORE PERFORMANCE
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nocompatible
set lazyredraw
set ttyfast
set updatetime=300
set shortmess+=c

" VSCode-like completion behavior
set completeopt=menuone,noinsert

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => PLUGIN MANAGER (vim-plug)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let plug_path = expand('~/.vim/autoload/plug.vim')

if empty(glob(plug_path))
  silent execute '!curl -fLo ' . plug_path . ' --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'

  augroup PlugBootstrap
    autocmd!
    autocmd VimEnter * ++once PlugInstall --sync | source $MYVIMRC
  augroup END
endif

call plug#begin('~/.vim/plugged')

" UI
Plug 'morhetz/gruvbox'
Plug 'vim-airline/vim-airline'

" File explorer
Plug 'preservim/nerdtree'

" Git
Plug 'tpope/vim-fugitive'
Plug 'airblade/vim-gitgutter'

" Editing
Plug 'jiangmiao/auto-pairs'
Plug 'nathanaelkane/vim-indent-guides'
Plug 'tpope/vim-commentary'
Plug 'tpope/vim-surround'
Plug 'christoomey/vim-tmux-navigator'

" FZF
Plug '/opt/homebrew/opt/fzf'
Plug 'junegunn/fzf.vim'

" Autocomplete (VSCode-like)
Plug 'neoclide/coc.nvim', {'branch': 'release'}

" Icons (must be last)
Plug 'ryanoasis/vim-devicons'

call plug#end()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => GENERAL
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set encoding=utf-8
set history=1000
filetype plugin on
filetype indent on

set autoread
au FocusGained,BufEnter * checktime

let mapleader="`"

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => UI
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set number
set mouse=a
set ruler
set clipboard=unnamed
set signcolumn=yes
set cmdheight=1
set hidden
set wildmenu
set pumheight=15
set showmatch
set so=7

" Cursor shape: bar in insert, block in normal
let &t_SI = "\e[6 q"
let &t_SR = "\e[4 q"
let &t_EI = "\e[2 q"

set ignorecase
set smartcase
set hlsearch
set incsearch

syntax enable
set background=dark
colorscheme gruvbox

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => FILES
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set nobackup
set nowritebackup
set noswapfile

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => INDENTATION
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set expandtab
set shiftwidth=4
set tabstop=4
set autoindent
set smartindent

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => KEY MAPPINGS
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Save
nnoremap <leader>w :w!<CR>

" NERDTree toggle
nnoremap <C-n> :NERDTreeToggle<CR>


" FZF
nnoremap <leader>f :Files<CR>
nnoremap <leader>b :Buffers<CR>
nnoremap <leader>r :Rg<CR>
nnoremap <leader>h :History<CR>

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => COC AUTOCOMPLETE (VS CODE STYLE)
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Use Tab / Shift-Tab to navigate popup
inoremap <silent><expr> <Tab> coc#pum#visible() ? coc#pum#next(1) : coc#refresh()
inoremap <silent><expr> <S-Tab> coc#pum#visible() ? coc#pum#prev(1) : "\<C-h>"

" Enter confirms selection
inoremap <silent><expr> <CR> coc#pum#visible() ? coc#pum#confirm() : "\<CR>"

" Trigger completion manually
inoremap <silent><expr> <C-Space> coc#refresh()

" Optional navigation
inoremap <expr> <C-j> coc#pum#visible() ? coc#pum#next(1) : "\<C-j>"
inoremap <expr> <C-k> coc#pum#visible() ? coc#pum#prev(1) : "\<C-k>"

" Highlight symbol like VS Code
autocmd CursorHold * silent call CocActionAsync('highlight')

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => STATUSLINE
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
set laststatus=2
let g:airline_theme='gruvbox'
let g:airline_powerline_fonts=1

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => AUTO CLEAN WHITESPACE
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
function! CleanExtraSpaces()
  let save_cursor = getpos(".")
  silent! %s/\s\+$//e
  call setpos('.', save_cursor)
endfunction

autocmd BufWritePre * call CleanExtraSpaces()

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" => COC EXTENSIONS
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:coc_global_extensions = [
      \ 'coc-tsserver',
      \ 'coc-json',
      \ 'coc-html',
      \ 'coc-css',
      \ 'coc-emmet'
      \ ]