#sudo pmset -a standby 0
#sudo pmset -a halfdim 0
#sudo pmset -a proximitywake 0
#sudo pmset -a powernap 0
#sudo pmset -a disksleep 10
#sudo pmset -a sleep 5
#sudo pmset -a hibernatemode 0
#sudo pmset -a displaysleep 5
#sudo pmset -a tcpkeepalive 0
#sudo pmset -a ttyskeepawake 1
#sudo pmset -a acwake 0
#sudo pmset -a lidwake 1